version: '3.8'
services:

  postgres-db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - ${PGPORT}:5432